### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by munakaya** [Cryptonomic/Arronax#58]
I tried to build but failed .

npm install webpack  
npm start

`user@user-VirtualBox:~/Arronax$ npm start

> Arronax@0.1.0 start /home/user/Arronax
> react-scripts-ts start

Starting type checking and linting service...
Using 1 worker with 2048MB memory limit
Watching: /home/user/Arronax/src
Cannot read property 'thisCompilation' of undefined
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Arronax@0.1.0 start: `react-scripts-ts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Arronax@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2018-09-18T10_49_43_681Z-debug.log
user@user-VirtualBox:~/Arronax$ 

cat  /home/user/.npm/_logs/2018-09-18T10_52_22_482Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.4.1
3 info using node@v8.12.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle Arronax@0.1.0~prestart: Arronax@0.1.0
6 info lifecycle Arronax@0.1.0~start: Arronax@0.1.0
7 verbose lifecycle Arronax@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle Arronax@0.1.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/user/Arronax/node_modules/.bin:/home/user/.opam/4.06.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle Arronax@0.1.0~start: CWD: /home/user/Arronax
10 silly lifecycle Arronax@0.1.0~start: Args: [ '-c', 'react-scripts-ts start' ]
11 silly lifecycle Arronax@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle Arronax@0.1.0~start: Failed to exec start script
13 verbose stack Error: Arronax@0.1.0 start: `react-scripts-ts start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid Arronax@0.1.0
15 verbose cwd /home/user/Arronax
16 verbose Linux 4.15.0-34-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v8.12.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error Arronax@0.1.0 start: `react-scripts-ts start`
22 error Exit status 1
23 error Failed at the Arronax@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

`

**Comment by munakaya** [comment]
yarn
npm start
